### ISSUE TITLE
Auto-upgrading `sapmachine14-ea-jdk` fails due to missing download.

### ISSUE THREAD

**Issue by pthariensflame** [SAP/homebrew-SapMachine#2]
This is basically a repeat of #1, I think, just on a different release.

**Comment by pthariensflame** [comment]
@RealCLanger @reshnm Since you two responded last time?

**Comment by RealCLanger** [comment]
I know, I‘m working on it. There are some infrastructure issues with our Macs. Will update the ticket when it’s resolved...


Am 11.07.2020 um 09:53 schrieb Alexander Ronald Altman <notifications@github.com>:

﻿

@RealCLanger<https://github.com/RealCLanger> @reshnm<https://github.com/reshnm> Since you two responded last time?

**Comment by RealCLanger** [comment]
Should be fixed now. :)

**Comment by pthariensflame** [comment]
Thanks so much!
