### ISSUE TITLE
SAP Machine 17 - JDK15 - unable to run ant clean all on SAP Commerce 2005

### ISSUE THREAD

**Issue by sorinache** [SAP/homebrew-SapMachine#9]
Hello,

We are currently running SAP Commerce 2005 on top of SAPMachine.  

Today I tried to build the project using SAPMachine17 for MAC OS M1 chip architecture and unfortunately I couldn't get the build pass.

`hybris/docker/hybris/bin/platform/resources/ant/mavenTasks.xml:201: java.lang.IllegalAccessError: class com.oopsconsultancy.xmltask.jdk15.XPathAnalyser15 (in unnamed module @0x272113c4) cannot access class com.sun.org.apache.xpath.internal.XPathAPI (in module java.xml) because module java.xml does not export com.sun.org.apache.xpath.internal to unnamed module @0x272113c4
	at com.oopsconsultancy.xmltask.jdk15.XPathAnalyser15.analyse(XPathAnalyser15.java:28)
	at com.oopsconsultancy.xmltask.XmlReplace.apply(XmlReplace.java:72)
	at com.oopsconsultancy.xmltask.XmlReplacement.apply(XmlReplacement.java:61)
	at com.oopsconsultancy.xmltask.ant.XmlTask.processDoc(XmlTask.java:692)
	at com.oopsconsultancy.xmltask.ant.XmlTask.execute(XmlTask.java:661)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)`

Above is the error received each time during ant clean.  It seems this is a missing dependency due to JDK 15 version (everything is fine on JDK 11). 

Can you please let us know how can we add this dependency manually.

Thanks,
Sorin

**Comment by RealCLanger** [comment]
Hi Sorin,

thanks for reporting this issue - although on a strange repository ;-) I would rather have expected this on https://github.com/SAP/SapMachine. 😉 

Nevertheless, I'm pretty sure that what you are seeing is related to the strong encapsulation of JDK internals. I would supsect it breaks already with SapMachine 16, due to https://openjdk.java.net/jeps/396. Now with SapMachine 17 we even have https://openjdk.java.net/jeps/403. So I think, the last JDK this works in that way is SapMachine 15.

To overcome this, I suggest you do some Google research and see if ant fixed that problem already (or the library that com.oopsconsultancy.xmltask originates from). Maybe it helps updating ant and its components?

I'm closing this ticket now. As mentioned above, if you seek out for further help please consider opening an issue on https://github.com/SAP/SapMachine.

Best regards
Christoph
